services:
  nginx:
    image: nginx:latest
    container_name: nginx-1
    volumes:
      - /local/nginx/:/etc/nginx/

    # Use scoped x-key preferentially
    x-inline-shell123: |
      #!/bin/bash
      echo "---inline shell---"
      echo 'include "conf.d/vhosts/*.conf";' > /local/nginx/conf.d/vhosts.conf

    x-hooks:
      pre-deploy:
        - ["mkdir", "-p", "/local/nginx/conf.d/vhosts"]
        - ["docker", "compose", "cpi", "nginx", "/etc/nginx:/local"]
        - ["shell-key", "x-inline-shell123"]
	- ["shell-key", "x-global-shell456"]


      post-deploy:
        - [ "echo", "----deployment successful----" ]
        - [ "sh", "-c", "echo 'Done' > 'result.txt'"]


# global x-key
x-global-shell456: |
  #!/bin/bash
  echo "---global shell---"